name: Build RedPill DSM loader

on: workflow_dispatch

jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build DS918+ 7.0
        id: build-ds918-70
        run: |
            bash build.sh

      - name: Archive DS918+ 7.0 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS918-7.0.1-loader
          path: output/redpill-DS918+_7.0.1*.img

